/**
 * Single-token sovereign-state names (ISO 3166 English short forms). Support and
 * CRM prose annotates a customer's nationality or location in parentheses right
 * after their name —
 * "Ingrid Bergman (Sweden)", "Klaus Müller (Germany)" — and the AKA-in-parens
 * cue in `detectors/names.ts` otherwise reads that bracketed word as an alias /
 * nickname and emits it as a PERSON. A country name in that appositive slot is a
 * geographic annotation, not a person, so it is guarded here.
 *
 * Why a curated list rather than a structural rule: nothing in the surface shape
 * distinguishes "(Sweden)" from a genuine nickname "(Johann)" — both are single
 * Cap-initial Latin tokens — so the geographic sense can only be recognised by
 * vocabulary. This is a closed, public-domain set (national short names change
 * rarely), so the list generalises to every `<Name> (<Country>)` case, including
 * countries the corpus has never carried, without touching name data.
 *
 * Deliberately EXCLUDED: country names that are also established personal given
 * names — "Chad", "Georgia", "Jordan", "India", "Ireland", "Israel". In the
 * `<Name> (X)` alias frame those are genuinely ambiguous, and under precision-
 * first we would rather keep detecting a plausible person than suppress one on a
 * word that is at least as often a name. None of these six is in the name DB, so
 * they detect only via this heuristic anyway; leaving them out keeps the guard
 * to unambiguously geographic tokens. Stored lowercased.
 */
export const COUNTRY_NAMES = new Set<string>([
  'afghanistan',
  'albania',
  'algeria',
  'andorra',
  'angola',
  'argentina',
  'armenia',
  'australia',
  'austria',
  'azerbaijan',
  'bahamas',
  'bahrain',
  'bangladesh',
  'barbados',
  'belarus',
  'belgium',
  'belize',
  'benin',
  'bhutan',
  'bolivia',
  'botswana',
  'brazil',
  'brunei',
  'bulgaria',
  'burundi',
  'cambodia',
  'cameroon',
  'canada',
  'chile',
  'china',
  'colombia',
  'comoros',
  'congo',
  'croatia',
  'cuba',
  'cyprus',
  'denmark',
  'djibouti',
  'dominica',
  'ecuador',
  'egypt',
  'eritrea',
  'estonia',
  'eswatini',
  'ethiopia',
  'fiji',
  'finland',
  'france',
  'gabon',
  'gambia',
  'germany',
  'ghana',
  'greece',
  'grenada',
  'guatemala',
  'guinea',
  'guyana',
  'haiti',
  'honduras',
  'hungary',
  'iceland',
  'indonesia',
  'iran',
  'iraq',
  'italy',
  'jamaica',
  'japan',
  'kazakhstan',
  'kenya',
  'kiribati',
  'kosovo',
  'kuwait',
  'kyrgyzstan',
  'laos',
  'latvia',
  'lebanon',
  'lesotho',
  'liberia',
  'libya',
  'liechtenstein',
  'lithuania',
  'luxembourg',
  'madagascar',
  'malawi',
  'malaysia',
  'maldives',
  'mali',
  'malta',
  'mauritania',
  'mauritius',
  'mexico',
  'micronesia',
  'moldova',
  'monaco',
  'mongolia',
  'montenegro',
  'morocco',
  'mozambique',
  'myanmar',
  'namibia',
  'nauru',
  'nepal',
  'netherlands',
  'nicaragua',
  'niger',
  'nigeria',
  'norway',
  'oman',
  'pakistan',
  'palau',
  'panama',
  'paraguay',
  'peru',
  'philippines',
  'poland',
  'portugal',
  'qatar',
  'romania',
  'russia',
  'rwanda',
  'samoa',
  'senegal',
  'serbia',
  'seychelles',
  'singapore',
  'slovakia',
  'slovenia',
  'somalia',
  'spain',
  'sudan',
  'suriname',
  'sweden',
  'switzerland',
  'syria',
  'taiwan',
  'tajikistan',
  'tanzania',
  'thailand',
  'togo',
  'tonga',
  'tunisia',
  'turkey',
  'turkmenistan',
  'tuvalu',
  'uganda',
  'ukraine',
  'uruguay',
  'uzbekistan',
  'vanuatu',
  'venezuela',
  'vietnam',
  'yemen',
  'zambia',
  'zimbabwe',
]);

/** Membership test for one already-lowercased token. */
export function isCountryName(lower: string): boolean {
  return COUNTRY_NAMES.has(lower);
}
