/**
 * Ordinary English words that routinely OPEN a clause in support / business prose
 * — imperatives ("Call", "Forward"), greetings & sign-offs ("Dear", "Regards"),
 * connectives ("However", "Regarding"), letter/ticket-header words ("From",
 * "Subject"), and clause-leading adjectives / temporal words ("Best", "Daily").
 *
 * Why this exists: the long-tail (ext) name lists are noisy — dozens of these
 * everyday words are also tagged as given/family names ("ask", "call", "best",
 * "dear", "note", "service" all read as DB hits). So DB membership alone cannot
 * tell "Call Maria" (a verb + a name) from "Bahar Mehrabad" (a real full name).
 * The name detector lets an ext-tier token START a chain at a sentence boundary
 * only when a following name part corroborates it; this guard list removes the
 * common-word anchors that would otherwise sneak through that path
 * ("Best Regards", "Call Maria", "Forward Johnson"). It only ever SUPPRESSES an
 * anchor at a sentence start, so a genuine surname appearing here as a *second*
 * part is unaffected ("John Best" still detects). Stored lowercased.
 */
export const SENTENCE_OPENERS = new Set<string>([
  // articles / determiners / quantifiers (a name never starts with one)
  'the',
  'a',
  'an',
  'this',
  'that',
  'these',
  'those',
  'each',
  'every',
  'any',
  'all',
  'some',
  'no',
  'both',
  'either',
  'neither',
  'another',
  'such',
  'one',
  'two',
  // possessives / pronouns
  'my',
  'our',
  'your',
  'their',
  'his',
  'her',
  'its',
  'we',
  'i',
  'you',
  'they',
  'he',
  'she',
  'it',
  'who',
  'whom',
  'whose',
  'what',
  'which',
  'when',
  'where',
  'why',
  // common auxiliaries / prepositions / conjunctions that open a clause
  'is',
  'are',
  'was',
  'were',
  'be',
  'been',
  'do',
  'does',
  'did',
  'has',
  'have',
  'had',
  'will',
  'would',
  'shall',
  'should',
  'can',
  'could',
  'may',
  'might',
  'must',
  'as',
  'at',
  'in',
  'on',
  'of',
  'if',
  'for',
  'with',
  'by',
  'and',
  'or',
  'but',
  'so',
  'not',
  'here',
  'there',
  // imperatives / common action verbs that open a sentence
  'ask',
  'reach',
  'forward',
  'call',
  'check',
  'see',
  'send',
  'set',
  'keep',
  'let',
  'find',
  'get',
  'take',
  'make',
  'give',
  'note',
  'contact',
  'review',
  'update',
  // Imperative verbs that routinely take a PERSON object in support / business
  // prose. They are not in the name DB themselves, but capitalize at a sentence
  // start the same way a given name does, so without listing them they would
  // anchor the backward-unknown-cap chain rule and slurp the following name
  // into a single FP span (e.g. "Email Volkov today" → "Email Volkov").
  'email',
  'visit',
  'meet',
  'page',
  'ping',
  'message',
  'mention',
  'invite',
  'tell',
  'talk',
  'confirm',
  'verify',
  'ensure',
  'follow',
  'refer',
  'attach',
  'submit',
  'file',
  'cancel',
  'book',
  'fix',
  'escalate',
  'process',
  'raise',
  'log',
  'track',
  'monitor',
  'flag',
  'notify',
  'alert',
  'inform',
  'advise',
  'remind',
  'schedule',
  'ship',
  'deliver',
  'return',
  'replace',
  'repair',
  'resolve',
  'help',
  'assist',
  'handle',
  'manage',
  'open',
  'close',
  'complete',
  'approve',
  'reject',
  'receive',
  'create',
  'remove',
  'add',
  'apply',
  'use',
  'try',
  'read',
  // greetings / sign-offs
  'hi',
  'hey',
  'hello',
  'dear',
  'cheers',
  'regards',
  'regard',
  'thanks',
  'thank',
  'sincerely',
  'greetings',
  // connectives / discourse markers
  'also',
  'however',
  'additionally',
  'furthermore',
  'moreover',
  'therefore',
  'thus',
  'hence',
  'meanwhile',
  'otherwise',
  'regarding',
  'concerning',
  'accordingly',
  'anyway',
  'regardless',
  'per',
  'via',
  're',
  'fwd',
  'fyi',
  'attn',
  // letter / ticket header words
  'from',
  'to',
  'cc',
  'bcc',
  'sent',
  'subject',
  'date',
  'action',
  'reason',
  'priority',
  'reminder',
  // clause-leading adjectives / determiners / temporal words
  'best',
  'new',
  'good',
  'great',
  'main',
  'key',
  'major',
  'minor',
  'high',
  'low',
  'top',
  'first',
  'last',
  'final',
  'next',
  'previous',
  'current',
  'recent',
  'latest',
  'urgent',
  'important',
  'daily',
  'weekly',
  'monthly',
  'today',
  'tomorrow',
  'yesterday',
  'soon',
  'now',
  'then',
  'finally',
  'initially',
  'currently',
  'recently',
]);

/** True for a clause-opener that must not, on its own, anchor a name chain. */
export function isSentenceOpener(token: string): boolean {
  return SENTENCE_OPENERS.has(token.toLowerCase());
}
