/**
 * Representative multilingual seed lists for v1 (M1). These are intentionally
 * small — the full coverage comes from the Bloom-filter language packs built by
 * scripts/build-db (M2+). Everything is lowercased. Latin entries cover European
 * plus transliterated Indian / Arabic / Hebrew / Persian / Chinese (Pinyin) /
 * Japanese (Romaji) names; a few native-script entries prove the non-Latin path.
 */

export const GIVEN_NAMES: string[] = [
  // German
  'hans',
  'kai',
  'uwe',
  'klaus',
  'jürgen',
  'wolfgang',
  'dieter',
  'lukas',
  'lena',
  'anna',
  'julia',
  'sophie',
  'emma',
  'kai-uwe',
  // English
  'john',
  'james',
  'robert',
  'michael',
  'william',
  'david',
  'mary',
  'patricia',
  'jennifer',
  'linda',
  'oliver',
  'emily',
  'george',
  'thomas',
  // French
  'jean',
  'pierre',
  'michel',
  'claire',
  'antoine',
  'camille',
  // Spanish
  'jose',
  'juan',
  'carlos',
  'maria',
  'sofia',
  'diego',
  // Italian
  'marco',
  'luca',
  'giuseppe',
  'francesca',
  'giulia',
  // Portuguese
  'joao',
  'pedro',
  'mateus',
  'beatriz',
  // Dutch / Polish
  'jan',
  'pieter',
  'sanne',
  'piotr',
  'katarzyna',
  'agnieszka',
  // Indian (transliterated)
  'priya',
  'rajesh',
  'arjun',
  'anjali',
  'ravi',
  'sanjay',
  'deepak',
  'kavya',
  'aditya',
  'lakshmi',
  // Arabic (transliterated)
  'mohammed',
  'ahmed',
  'omar',
  'ali',
  'fatima',
  'aisha',
  'yusuf',
  'ibrahim',
  'khalid',
  'farah',
  // Hebrew (transliterated)
  'moshe',
  'sarah',
  'rivka',
  'yosef',
  'noa',
  'avraham',
  // Persian (transliterated)
  'reza',
  'farhad',
  'leila',
  'kourosh',
  'darius',
  'parisa',
  // Chinese (Pinyin)
  'wei',
  'fang',
  'jing',
  'lei',
  'ming',
  'yan',
  'hui',
  'na',
  // Japanese (Romaji)
  'haruki',
  'takashi',
  'yuki',
  'akira',
  'hiroshi',
  'kenji',
  'sakura',
  'yuna',
  // Native-script samples
  'محمد',
  'علي',
  'فاطمة',
  'דוד',
  'שרה',
  'प्रिया',
  'अर्जुन',
];

export const FAMILY_NAMES: string[] = [
  // German
  'müller',
  'schmidt',
  'schneider',
  'braun',
  'weber',
  'fischer',
  'wagner',
  'becker',
  'hoffmann',
  // English
  'smith',
  'johnson',
  'williams',
  'jones',
  'davis',
  'wilson',
  'taylor',
  'anderson',
  'thomas',
  // French
  'martin',
  'bernard',
  'dubois',
  'durand',
  // Spanish
  'garcia',
  'rodriguez',
  'gonzalez',
  'fernandez',
  'lopez',
  // Italian
  'rossi',
  'russo',
  'ferrari',
  'esposito',
  // Portuguese
  'silva',
  'santos',
  'oliveira',
  'souza',
  // Dutch / Polish
  'jansen',
  'visser',
  'nowak',
  'kowalski',
  'wisniewski',
  // Indian (transliterated)
  'sharma',
  'patel',
  'singh',
  'kumar',
  'gupta',
  'reddy',
  'nair',
  'rao',
  // Arabic (transliterated)
  'farouk',
  'hassan',
  'khalil',
  'said',
  'mansour',
  // Hebrew (transliterated)
  'cohen',
  'levi',
  'mizrahi',
  'peretz',
  'gurion',
  // Persian (transliterated)
  'tehrani',
  'ahmadi',
  'hosseini',
  'karimi',
  // Chinese (Pinyin)
  'wang',
  'li',
  'zhang',
  'liu',
  'chen',
  'huang',
  'zhao',
  'zhou',
  // Japanese (Romaji)
  'sato',
  'suzuki',
  'takahashi',
  'tanaka',
  'watanabe',
  'yamamoto',
  'nakamura',
  'kobayashi',
  'murakami',
  // Native-script samples
  'حسن',
  'כהן',
  'לוי',
  'शर्मा',
  'पटेल',
];
