/**
 * Writes docs/metrics.md — a generated snapshot of the name database the build
 * produces (total names, per-script/per-tier breakdown, byte sizes). Run after
 * `npm run build:db`:
 *
 *   npm run metrics
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { ALL_PII_TYPES } from '../src/core/types';

const here = dirname(fileURLToPath(import.meta.url));
const manifestPath = join(here, '..', 'public', 'packs', 'packs.json');

interface Pack {
  name: string;
  script: string;
  tier: string;
  count: number;
  bytes: number;
}

const manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as {
  generated: string;
  packs: Pack[];
};

const fmt = (n: number) => n.toLocaleString('en-US');
const total = manifest.packs.reduce((s, p) => s + p.count, 0);
const totalBytes = manifest.packs.reduce((s, p) => s + p.bytes, 0);
const scripts = [...new Set(manifest.packs.map((p) => p.script))];

const rows = manifest.packs
  .map((p) => `| ${p.name} | ${p.script} | ${p.tier} | ${fmt(p.count)} | ${fmt(p.bytes)} |`)
  .join('\n');

const md = `# Metrics snapshot

<!-- Generated by \`npm run metrics\` (scripts/report-metrics.ts). Do not edit by hand. -->

Packs generated: ${manifest.generated}

- **PII types detected:** ${ALL_PII_TYPES.length} (${ALL_PII_TYPES.join(', ')})
- **Names in the database:** ${fmt(total)} across ${manifest.packs.length} packs
- **Scripts covered:** ${scripts.length} (${scripts.join(', ')})
- **Total pack size:** ${fmt(totalBytes)} bytes (compact Bloom filters, shipped read-only)

| Pack | Script | Tier | Names | Bytes |
| --- | --- | --- | --- | --- |
${rows}
| **Total** | | | **${fmt(total)}** | **${fmt(totalBytes)}** |

The database grows continuously via the [self-improvement loop](self-improve.md):
the expansion layer adds names from public, permissively licensed sources, while the
discovery layer ships generalizing heuristic fixes (no name dumps).
`;

const out = join(here, '..', 'docs', 'metrics.md');
writeFileSync(out, md);
console.log(`Wrote ${out} — ${fmt(total)} names across ${manifest.packs.length} packs.`);
